import { ADDITIONAL_BURN_RUNWAY_SCENARIOS } from "./burn-runway-scenarios";
import { ADDITIONAL_REVENUE_GROWTH_SCENARIOS } from "./revenue-growth-scenarios";
import { ADDITIONAL_VALUATION_OWNERSHIP_SCENARIOS } from "./valuation-ownership-scenarios";

export interface MetricTile {
  id: string;
  label: string;
}

export interface MetricSlot {
  id: string;
  label: string;
  correctTileId: string;
  explanation: string;
  calculation: string;
}

export type DealRoomSection =
  | "unit-economics"
  | "revenue-growth"
  | "burn-runway"
  | "valuation-ownership";

export const DEAL_ROOM_SECTIONS: readonly DealRoomSection[] = [
  "unit-economics",
  "revenue-growth",
  "burn-runway",
  "valuation-ownership",
];

export const DEAL_ROOM_SECTION_LABELS: Record<DealRoomSection, string> = {
  "unit-economics": "Unit Economics",
  "revenue-growth": "Revenue & Growth",
  "burn-runway": "Burn & Runway",
  "valuation-ownership": "Valuation & Ownership",
};

export interface MathPuzzleScenario {
  id: string;
  section: DealRoomSection;
  startupName: string;
  rawInputs: { label: string; value: string }[];
  slots: MetricSlot[];
  tilePool: MetricTile[];
  verdict: string;
  verdictType: "healthy" | "concerning" | "unsustainable";
}

export const MATH_PUZZLE_SCENARIOS: readonly MathPuzzleScenario[] = [
  {
    id: "ledger-loop",
    section: "unit-economics",
    startupName: "LedgerLoop",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$100" },
      { label: "Customer Acquisition Cost", value: "$800" },
      { label: "Gross Margin", value: "80%" },
      { label: "Monthly Churn Rate", value: "2%" },
    ],
    slots: [
      {
        id: "ledger-loop-ltv",
        label: "LTV",
        correctTileId: "ledger-loop-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($100 × 80%) ÷ 2% = $4,000",
      },
      {
        id: "ledger-loop-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "ledger-loop-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$4,000 ÷ $800 = 5.0x",
      },
      {
        id: "ledger-loop-payback",
        label: "Payback Period",
        correctTileId: "ledger-loop-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$800 ÷ ($100 × 80%) = 10 months",
      },
    ],
    tilePool: [
      { id: "ledger-loop-ltv-correct", label: "$4,000" },
      { id: "ledger-loop-ltv-wrong-1", label: "$5,000" },
      { id: "ledger-loop-ltv-wrong-2", label: "$3,200" },
      { id: "ledger-loop-ratio-correct", label: "5.0x" },
      { id: "ledger-loop-ratio-wrong-1", label: "6.3x" },
      { id: "ledger-loop-ratio-wrong-2", label: "4.0x" },
      { id: "ledger-loop-payback-correct", label: "10 months" },
      { id: "ledger-loop-payback-wrong-1", label: "8 months" },
      { id: "ledger-loop-payback-wrong-2", label: "12.5 months" },
    ],
    verdict: "A 5.0x LTV:CAC ratio and 10-month payback indicate strong subscription unit economics. The company has room to reinvest in acquisition, although the churn assumption should still be validated across customer cohorts.",
    verdictType: "healthy",
  },
  {
    id: "crew-signal",
    section: "unit-economics",
    startupName: "CrewSignal",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$75" },
      { label: "Customer Acquisition Cost", value: "$500" },
      { label: "Gross Margin", value: "80%" },
      { label: "Monthly Churn Rate", value: "3%" },
    ],
    slots: [
      {
        id: "crew-signal-ltv",
        label: "LTV",
        correctTileId: "crew-signal-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($75 × 80%) ÷ 3% = $2,000",
      },
      {
        id: "crew-signal-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "crew-signal-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$2,000 ÷ $500 = 4.0x",
      },
      {
        id: "crew-signal-payback",
        label: "Payback Period",
        correctTileId: "crew-signal-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$500 ÷ ($75 × 80%) ≈ 8.3 months",
      },
    ],
    tilePool: [
      { id: "crew-signal-ltv-correct", label: "$2,000" },
      { id: "crew-signal-ltv-wrong-1", label: "$2,500" },
      { id: "crew-signal-ltv-wrong-2", label: "$1,600" },
      { id: "crew-signal-ratio-correct", label: "4.0x" },
      { id: "crew-signal-ratio-wrong-1", label: "5.0x" },
      { id: "crew-signal-ratio-wrong-2", label: "3.2x" },
      { id: "crew-signal-payback-correct", label: "8.3 months" },
      { id: "crew-signal-payback-wrong-1", label: "6.7 months" },
      { id: "crew-signal-payback-wrong-2", label: "10.4 months" },
    ],
    verdict: "A 4.0x LTV:CAC ratio with an 8.3-month payback suggests efficient acquisition and healthy retention economics. The next diligence question is whether these results hold as the company moves beyond its best-performing channels.",
    verdictType: "healthy",
  },
  {
    id: "vault-desk",
    section: "unit-economics",
    startupName: "VaultDesk",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$200" },
      { label: "Customer Acquisition Cost", value: "$1,800" },
      { label: "Gross Margin", value: "90%" },
      { label: "Monthly Churn Rate", value: "2.5%" },
    ],
    slots: [
      {
        id: "vault-desk-ltv",
        label: "LTV",
        correctTileId: "vault-desk-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($200 × 90%) ÷ 2.5% = $7,200",
      },
      {
        id: "vault-desk-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "vault-desk-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$7,200 ÷ $1,800 = 4.0x",
      },
      {
        id: "vault-desk-payback",
        label: "Payback Period",
        correctTileId: "vault-desk-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$1,800 ÷ ($200 × 90%) = 10 months",
      },
    ],
    tilePool: [
      { id: "vault-desk-ltv-correct", label: "$7,200" },
      { id: "vault-desk-ltv-wrong-1", label: "$8,000" },
      { id: "vault-desk-ltv-wrong-2", label: "$6,480" },
      { id: "vault-desk-ratio-correct", label: "4.0x" },
      { id: "vault-desk-ratio-wrong-1", label: "4.4x" },
      { id: "vault-desk-ratio-wrong-2", label: "3.6x" },
      { id: "vault-desk-payback-correct", label: "10 months" },
      { id: "vault-desk-payback-wrong-1", label: "9 months" },
      { id: "vault-desk-payback-wrong-2", label: "11.1 months" },
    ],
    verdict: "A 4.0x LTV:CAC ratio and 10-month payback are healthy for this high-margin subscription model. The economics support growth, provided enterprise sales costs and churn remain stable as the company scales.",
    verdictType: "healthy",
  },
  {
    id: "creator-flow",
    section: "unit-economics",
    startupName: "CreatorFlow",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$40" },
      { label: "Customer Acquisition Cost", value: "$300" },
      { label: "Gross Margin", value: "75%" },
      { label: "Monthly Churn Rate", value: "5%" },
    ],
    slots: [
      {
        id: "creator-flow-ltv",
        label: "LTV",
        correctTileId: "creator-flow-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($40 × 75%) ÷ 5% = $600",
      },
      {
        id: "creator-flow-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "creator-flow-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$600 ÷ $300 = 2.0x",
      },
      {
        id: "creator-flow-payback",
        label: "Payback Period",
        correctTileId: "creator-flow-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$300 ÷ ($40 × 75%) = 10 months",
      },
    ],
    tilePool: [
      { id: "creator-flow-ltv-correct", label: "$600" },
      { id: "creator-flow-ltv-wrong-1", label: "$800" },
      { id: "creator-flow-ltv-wrong-2", label: "$450" },
      { id: "creator-flow-ratio-correct", label: "2.0x" },
      { id: "creator-flow-ratio-wrong-1", label: "2.7x" },
      { id: "creator-flow-ratio-wrong-2", label: "1.5x" },
      { id: "creator-flow-payback-correct", label: "10 months" },
      { id: "creator-flow-payback-wrong-1", label: "7.5 months" },
      { id: "creator-flow-payback-wrong-2", label: "13.3 months" },
    ],
    verdict: "The 10-month payback is reasonably quick, but a 2.0x LTV:CAC ratio leaves limited lifetime gross profit after acquisition. Better retention or cheaper acquisition would create a safer growth model.",
    verdictType: "concerning",
  },
  {
    id: "clinic-relay",
    section: "unit-economics",
    startupName: "ClinicRelay",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$250" },
      { label: "Customer Acquisition Cost", value: "$1,875" },
      { label: "Gross Margin", value: "60%" },
      { label: "Monthly Churn Rate", value: "4%" },
    ],
    slots: [
      {
        id: "clinic-relay-ltv",
        label: "LTV",
        correctTileId: "clinic-relay-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($250 × 60%) ÷ 4% = $3,750",
      },
      {
        id: "clinic-relay-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "clinic-relay-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$3,750 ÷ $1,875 = 2.0x",
      },
      {
        id: "clinic-relay-payback",
        label: "Payback Period",
        correctTileId: "clinic-relay-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$1,875 ÷ ($250 × 60%) = 12.5 months",
      },
    ],
    tilePool: [
      { id: "clinic-relay-ltv-correct", label: "$3,750" },
      { id: "clinic-relay-ltv-wrong-1", label: "$6,250" },
      { id: "clinic-relay-ltv-wrong-2", label: "$2,250" },
      { id: "clinic-relay-ratio-correct", label: "2.0x" },
      { id: "clinic-relay-ratio-wrong-1", label: "3.3x" },
      { id: "clinic-relay-ratio-wrong-2", label: "1.2x" },
      { id: "clinic-relay-payback-correct", label: "12.5 months" },
      { id: "clinic-relay-payback-wrong-1", label: "7.5 months" },
      { id: "clinic-relay-payback-wrong-2", label: "20.8 months" },
    ],
    verdict: "A 12.5-month payback may be workable for a healthcare software company, but the 2.0x LTV:CAC ratio provides limited protection against longer sales cycles or weaker retention. The economics need improvement before aggressive expansion.",
    verdictType: "concerning",
  },
  {
    id: "field-stack",
    section: "unit-economics",
    startupName: "FieldStack",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$90" },
      { label: "Customer Acquisition Cost", value: "$810" },
      { label: "Gross Margin", value: "60%" },
      { label: "Monthly Churn Rate", value: "3%" },
    ],
    slots: [
      {
        id: "field-stack-ltv",
        label: "LTV",
        correctTileId: "field-stack-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($90 × 60%) ÷ 3% = $1,800",
      },
      {
        id: "field-stack-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "field-stack-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$1,800 ÷ $810 ≈ 2.2x",
      },
      {
        id: "field-stack-payback",
        label: "Payback Period",
        correctTileId: "field-stack-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$810 ÷ ($90 × 60%) = 15 months",
      },
    ],
    tilePool: [
      { id: "field-stack-ltv-correct", label: "$1,800" },
      { id: "field-stack-ltv-wrong-1", label: "$3,000" },
      { id: "field-stack-ltv-wrong-2", label: "$1,080" },
      { id: "field-stack-ratio-correct", label: "2.2x" },
      { id: "field-stack-ratio-wrong-1", label: "3.7x" },
      { id: "field-stack-ratio-wrong-2", label: "1.3x" },
      { id: "field-stack-payback-correct", label: "15 months" },
      { id: "field-stack-payback-wrong-1", label: "9 months" },
      { id: "field-stack-payback-wrong-2", label: "25 months" },
    ],
    verdict: "A 2.2x LTV:CAC ratio and 15-month payback make growth possible but capital-intensive. The company should prove that acquisition costs will not rise as it expands into less efficient channels.",
    verdictType: "concerning",
  },
  {
    id: "box-bright",
    section: "unit-economics",
    startupName: "BoxBright",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$30" },
      { label: "Customer Acquisition Cost", value: "$300" },
      { label: "Gross Margin", value: "50%" },
      { label: "Monthly Churn Rate", value: "10%" },
    ],
    slots: [
      {
        id: "box-bright-ltv",
        label: "LTV",
        correctTileId: "box-bright-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($30 × 50%) ÷ 10% = $150",
      },
      {
        id: "box-bright-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "box-bright-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$150 ÷ $300 = 0.5x",
      },
      {
        id: "box-bright-payback",
        label: "Payback Period",
        correctTileId: "box-bright-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$300 ÷ ($30 × 50%) = 20 months",
      },
    ],
    tilePool: [
      { id: "box-bright-ltv-correct", label: "$150" },
      { id: "box-bright-ltv-wrong-1", label: "$300" },
      { id: "box-bright-ltv-wrong-2", label: "$75" },
      { id: "box-bright-ratio-correct", label: "0.5x" },
      { id: "box-bright-ratio-wrong-1", label: "1.0x" },
      { id: "box-bright-ratio-wrong-2", label: "0.3x" },
      { id: "box-bright-payback-correct", label: "20 months" },
      { id: "box-bright-payback-wrong-1", label: "10 months" },
      { id: "box-bright-payback-wrong-2", label: "40 months" },
    ],
    verdict: "The 0.5x LTV:CAC ratio means acquisition cost is twice the customer's gross-profit LTV. Customers are not expected to repay their acquisition cost before churning, so scaling this model would deepen losses.",
    verdictType: "unsustainable",
  },
  {
    id: "ad-pilot",
    section: "unit-economics",
    startupName: "AdPilot",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$60" },
      { label: "Customer Acquisition Cost", value: "$840" },
      { label: "Gross Margin", value: "70%" },
      { label: "Monthly Churn Rate", value: "7%" },
    ],
    slots: [
      {
        id: "ad-pilot-ltv",
        label: "LTV",
        correctTileId: "ad-pilot-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($60 × 70%) ÷ 7% = $600",
      },
      {
        id: "ad-pilot-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "ad-pilot-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$600 ÷ $840 ≈ 0.7x",
      },
      {
        id: "ad-pilot-payback",
        label: "Payback Period",
        correctTileId: "ad-pilot-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$840 ÷ ($60 × 70%) = 20 months",
      },
    ],
    tilePool: [
      { id: "ad-pilot-ltv-correct", label: "$600" },
      { id: "ad-pilot-ltv-wrong-1", label: "$857" },
      { id: "ad-pilot-ltv-wrong-2", label: "$420" },
      { id: "ad-pilot-ratio-correct", label: "0.7x" },
      { id: "ad-pilot-ratio-wrong-1", label: "1.0x" },
      { id: "ad-pilot-ratio-wrong-2", label: "0.5x" },
      { id: "ad-pilot-payback-correct", label: "20 months" },
      { id: "ad-pilot-payback-wrong-1", label: "14 months" },
      { id: "ad-pilot-payback-wrong-2", label: "28.6 months" },
    ],
    verdict: "The 0.7x LTV:CAC ratio means expected gross-profit value does not cover acquisition cost. The 20-month payback also extends beyond the customer lifetime implied by current churn, making paid growth unsustainable.",
    verdictType: "unsustainable",
  },
  {
    id: "care-assist",
    section: "unit-economics",
    startupName: "CareAssist",
    rawInputs: [
      { label: "Avg. Revenue Per Customer (monthly)", value: "$150" },
      { label: "Customer Acquisition Cost", value: "$1,200" },
      { label: "Gross Margin", value: "40%" },
      { label: "Monthly Churn Rate", value: "8%" },
    ],
    slots: [
      {
        id: "care-assist-ltv",
        label: "LTV",
        correctTileId: "care-assist-ltv-correct",
        explanation: "Estimates the gross-profit value generated by one customer before they churn.",
        calculation: "($150 × 40%) ÷ 8% = $750",
      },
      {
        id: "care-assist-ratio",
        label: "LTV:CAC Ratio",
        correctTileId: "care-assist-ratio-correct",
        explanation: "Compares customer value with the cost of acquiring that customer.",
        calculation: "$750 ÷ $1,200 ≈ 0.6x",
      },
      {
        id: "care-assist-payback",
        label: "Payback Period",
        correctTileId: "care-assist-payback-correct",
        explanation: "Shows how long it takes to recover the acquisition cost from gross profit.",
        calculation: "$1,200 ÷ ($150 × 40%) = 20 months",
      },
    ],
    tilePool: [
      { id: "care-assist-ltv-correct", label: "$750" },
      { id: "care-assist-ltv-wrong-1", label: "$1,875" },
      { id: "care-assist-ltv-wrong-2", label: "$300" },
      { id: "care-assist-ratio-correct", label: "0.6x" },
      { id: "care-assist-ratio-wrong-1", label: "1.6x" },
      { id: "care-assist-ratio-wrong-2", label: "0.3x" },
      { id: "care-assist-payback-correct", label: "20 months" },
      { id: "care-assist-payback-wrong-1", label: "8 months" },
      { id: "care-assist-payback-wrong-2", label: "50 months" },
    ],
    verdict: "The 0.6x LTV:CAC ratio means customer gross-profit value does not recover acquisition cost. A 20-month payback is also longer than the customer lifetime implied by 8% monthly churn, so the current acquisition model is unsustainable.",
    verdictType: "unsustainable",
  },
  {
    id: "pulse-desk",
    section: "revenue-growth",
    startupName: "PulseDesk",
    rawInputs: [
      { label: "Starting MRR", value: "$50K" },
      { label: "New MRR", value: "$15K" },
      { label: "Expansion MRR", value: "$5K" },
      { label: "Churned MRR", value: "$10K" },
    ],
    slots: [
      {
        id: "pulse-desk-mrr",
        label: "MRR",
        correctTileId: "pulse-desk-mrr-correct",
        explanation: "Monthly recurring revenue after new, expansion, and churned subscription revenue.",
        calculation: "$50K + $15K + $5K − $10K = $60K",
      },
      {
        id: "pulse-desk-arr",
        label: "ARR",
        correctTileId: "pulse-desk-arr-correct",
        explanation: "Annualized recurring revenue based on the current monthly run rate.",
        calculation: "$60K × 12 = $720K",
      },
      {
        id: "pulse-desk-growth",
        label: "Revenue Growth",
        correctTileId: "pulse-desk-growth-correct",
        explanation: "The percentage increase from starting MRR to current MRR.",
        calculation: "($60K − $50K) ÷ $50K = 20%",
      },
    ],
    tilePool: [
      { id: "pulse-desk-mrr-correct", label: "$60K" },
      { id: "pulse-desk-mrr-wrong-1", label: "$70K" },
      { id: "pulse-desk-mrr-wrong-2", label: "$50K" },
      { id: "pulse-desk-arr-correct", label: "$720K" },
      { id: "pulse-desk-arr-wrong-1", label: "$600K" },
      { id: "pulse-desk-arr-wrong-2", label: "$840K" },
      { id: "pulse-desk-growth-correct", label: "20%" },
      { id: "pulse-desk-growth-wrong-1", label: "10%" },
      { id: "pulse-desk-growth-wrong-2", label: "40%" },
    ],
    verdict:
      "MRR grew 20%, with new and expansion revenue comfortably exceeding churn. The recurring base is expanding, although churn still removes half of the gross additions and should be watched as the company scales.",
    verdictType: "healthy",
  },
  {
    id: "runway-works",
    section: "burn-runway",
    startupName: "RunwayWorks",
    rawInputs: [
      { label: "Cash Operating Expenses (quarter)", value: "$900K" },
      { label: "Cash Receipts (quarter)", value: "$300K" },
      { label: "Cash Balance", value: "$1.2M" },
      { label: "Net New ARR (quarter)", value: "$400K" },
    ],
    slots: [
      {
        id: "runway-works-net-burn",
        label: "Net Burn",
        correctTileId: "runway-works-net-burn-correct",
        explanation: "Cash consumed after operating cash receipts during the measured period.",
        calculation: "$900K − $300K = $600K per quarter",
      },
      {
        id: "runway-works-runway",
        label: "Runway",
        correctTileId: "runway-works-runway-correct",
        explanation: "Estimated time before the company exhausts its cash at the current burn rate.",
        calculation: "$1.2M ÷ ($600K ÷ 3) = 6 months",
      },
      {
        id: "runway-works-burn-multiple",
        label: "Burn Multiple",
        correctTileId: "runway-works-burn-multiple-correct",
        explanation: "Compares net cash burned with net new recurring revenue created in the same period.",
        calculation: "$600K ÷ $400K = 1.5x",
      },
    ],
    tilePool: [
      { id: "runway-works-net-burn-correct", label: "$600K / quarter" },
      { id: "runway-works-net-burn-wrong-1", label: "$900K / quarter" },
      { id: "runway-works-net-burn-wrong-2", label: "$300K / quarter" },
      { id: "runway-works-runway-correct", label: "6 months" },
      { id: "runway-works-runway-wrong-1", label: "2 months" },
      { id: "runway-works-runway-wrong-2", label: "4 months" },
      { id: "runway-works-burn-multiple-correct", label: "1.5x" },
      { id: "runway-works-burn-multiple-wrong-1", label: "2.3x" },
      { id: "runway-works-burn-multiple-wrong-2", label: "0.8x" },
    ],
    verdict:
      "The company has six months of runway and a 1.5x burn multiple. Cash efficiency is reasonable, but the short runway creates a near-term financing or cost-reduction deadline.",
    verdictType: "concerning",
  },
  {
    id: "roundwise",
    section: "valuation-ownership",
    startupName: "Roundwise",
    rawInputs: [
      { label: "Pre-money Valuation", value: "$8M" },
      { label: "New Investment", value: "$2M" },
      { label: "Founder Ownership Before Round", value: "80%" },
      { label: "Other Existing Ownership Before Round", value: "20%" },
    ],
    slots: [
      {
        id: "roundwise-post-money",
        label: "Post-money Valuation",
        correctTileId: "roundwise-post-money-correct",
        explanation: "The company valuation immediately after adding the new investment.",
        calculation: "$8M + $2M = $10M",
      },
      {
        id: "roundwise-investor-ownership",
        label: "Investor Ownership",
        correctTileId: "roundwise-investor-ownership-correct",
        explanation: "The new investor's share of the post-money company value.",
        calculation: "$2M ÷ $10M = 20%",
      },
      {
        id: "roundwise-founder-ownership",
        label: "Founder Ownership After Round",
        correctTileId: "roundwise-founder-ownership-correct",
        explanation: "The founder's remaining ownership after the new investor receives their stake.",
        calculation: "80% × (1 − 20%) = 64%",
      },
    ],
    tilePool: [
      { id: "roundwise-post-money-correct", label: "$10M" },
      { id: "roundwise-post-money-wrong-1", label: "$8M" },
      { id: "roundwise-post-money-wrong-2", label: "$6M" },
      { id: "roundwise-investor-ownership-correct", label: "20%" },
      { id: "roundwise-investor-ownership-wrong-1", label: "25%" },
      { id: "roundwise-investor-ownership-wrong-2", label: "16.7%" },
      { id: "roundwise-founder-ownership-correct", label: "64%" },
      { id: "roundwise-founder-ownership-wrong-1", label: "60%" },
      { id: "roundwise-founder-ownership-wrong-2", label: "80%" },
    ],
    verdict:
      "The investor receives 20% and founder ownership falls from 80% to 64%. The round preserves a founder majority, but it still consumes a meaningful part of the ownership available for future financing and hiring.",
    verdictType: "concerning",
  },
  ...ADDITIONAL_REVENUE_GROWTH_SCENARIOS,
  ...ADDITIONAL_BURN_RUNWAY_SCENARIOS,
  ...ADDITIONAL_VALUATION_OWNERSHIP_SCENARIOS,
];
