import type { MathPuzzleScenario } from "./math-puzzle-scenarios";

const MRR_EXPLANATION =
  "Monthly recurring revenue after new, expansion, and churned subscription revenue.";
const ARR_EXPLANATION =
  "Annualized recurring revenue based on the current monthly run rate.";
const GROWTH_EXPLANATION =
  "The percentage change from starting MRR to current MRR.";

export const ADDITIONAL_REVENUE_GROWTH_SCENARIOS: readonly MathPuzzleScenario[] = [
  {
    id: "team-beacon",
    section: "revenue-growth",
    startupName: "TeamBeacon",
    rawInputs: [
      { label: "Starting MRR", value: "$80K" },
      { label: "New MRR", value: "$20K" },
      { label: "Expansion MRR", value: "$8K" },
      { label: "Churned MRR", value: "$4K" },
    ],
    slots: [
      { id: "team-beacon-mrr", label: "MRR", correctTileId: "team-beacon-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$80K + $20K + $8K − $4K = $104K" },
      { id: "team-beacon-arr", label: "ARR", correctTileId: "team-beacon-arr-correct", explanation: ARR_EXPLANATION, calculation: "$104K × 12 = $1.248M" },
      { id: "team-beacon-growth", label: "Revenue Growth", correctTileId: "team-beacon-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($104K − $80K) ÷ $80K = 30%" },
    ],
    tilePool: [
      { id: "team-beacon-mrr-correct", label: "$104K" },
      { id: "team-beacon-mrr-wrong-1", label: "$108K" },
      { id: "team-beacon-mrr-wrong-2", label: "$96K" },
      { id: "team-beacon-arr-correct", label: "$1.248M" },
      { id: "team-beacon-arr-wrong-1", label: "$960K" },
      { id: "team-beacon-arr-wrong-2", label: "$1.04M" },
      { id: "team-beacon-growth-correct", label: "30%" },
      { id: "team-beacon-growth-wrong-1", label: "35%" },
      { id: "team-beacon-growth-wrong-2", label: "20%" },
    ],
    verdict: "MRR increased by 30%, with expansion exceeding churn. The recurring base is growing from both new and existing customers, although the company should confirm that this pace is durable across future periods.",
    verdictType: "healthy",
  },
  {
    id: "route-cloud",
    section: "revenue-growth",
    startupName: "RouteCloud",
    rawInputs: [
      { label: "Starting MRR", value: "$120K" },
      { label: "New MRR", value: "$18K" },
      { label: "Expansion MRR", value: "$6K" },
      { label: "Churned MRR", value: "$12K" },
    ],
    slots: [
      { id: "route-cloud-mrr", label: "MRR", correctTileId: "route-cloud-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$120K + $18K + $6K − $12K = $132K" },
      { id: "route-cloud-arr", label: "ARR", correctTileId: "route-cloud-arr-correct", explanation: ARR_EXPLANATION, calculation: "$132K × 12 = $1.584M" },
      { id: "route-cloud-growth", label: "Revenue Growth", correctTileId: "route-cloud-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($132K − $120K) ÷ $120K = 10%" },
    ],
    tilePool: [
      { id: "route-cloud-mrr-correct", label: "$132K" },
      { id: "route-cloud-mrr-wrong-1", label: "$144K" },
      { id: "route-cloud-mrr-wrong-2", label: "$126K" },
      { id: "route-cloud-arr-correct", label: "$1.584M" },
      { id: "route-cloud-arr-wrong-1", label: "$1.44M" },
      { id: "route-cloud-arr-wrong-2", label: "$1.32M" },
      { id: "route-cloud-growth-correct", label: "10%" },
      { id: "route-cloud-growth-wrong-1", label: "20%" },
      { id: "route-cloud-growth-wrong-2", label: "5%" },
    ],
    verdict: "Recurring revenue grew 10%, but churn absorbed half of the combined new and expansion MRR. Growth is positive, yet retention needs attention before the company relies on the current acquisition pace.",
    verdictType: "concerning",
  },
  {
    id: "tutor-nest",
    section: "revenue-growth",
    startupName: "TutorNest",
    rawInputs: [
      { label: "Starting MRR", value: "$40K" },
      { label: "New MRR", value: "$8K" },
      { label: "Expansion MRR", value: "$2K" },
      { label: "Churned MRR", value: "$6K" },
    ],
    slots: [
      { id: "tutor-nest-mrr", label: "MRR", correctTileId: "tutor-nest-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$40K + $8K + $2K − $6K = $44K" },
      { id: "tutor-nest-arr", label: "ARR", correctTileId: "tutor-nest-arr-correct", explanation: ARR_EXPLANATION, calculation: "$44K × 12 = $528K" },
      { id: "tutor-nest-growth", label: "Revenue Growth", correctTileId: "tutor-nest-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($44K − $40K) ÷ $40K = 10%" },
    ],
    tilePool: [
      { id: "tutor-nest-mrr-correct", label: "$44K" },
      { id: "tutor-nest-mrr-wrong-1", label: "$50K" },
      { id: "tutor-nest-mrr-wrong-2", label: "$42K" },
      { id: "tutor-nest-arr-correct", label: "$528K" },
      { id: "tutor-nest-arr-wrong-1", label: "$480K" },
      { id: "tutor-nest-arr-wrong-2", label: "$440K" },
      { id: "tutor-nest-growth-correct", label: "10%" },
      { id: "tutor-nest-growth-wrong-1", label: "25%" },
      { id: "tutor-nest-growth-wrong-2", label: "5%" },
    ],
    verdict: "MRR grew 10%, but churn erased most of the revenue added through new sales and expansion. The company is moving forward, though retention is limiting how efficiently that growth compounds.",
    verdictType: "concerning",
  },
  {
    id: "market-mint",
    section: "revenue-growth",
    startupName: "MarketMint",
    rawInputs: [
      { label: "Starting MRR", value: "$200K" },
      { label: "New MRR", value: "$30K" },
      { label: "Expansion MRR", value: "$20K" },
      { label: "Churned MRR", value: "$10K" },
    ],
    slots: [
      { id: "market-mint-mrr", label: "MRR", correctTileId: "market-mint-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$200K + $30K + $20K − $10K = $240K" },
      { id: "market-mint-arr", label: "ARR", correctTileId: "market-mint-arr-correct", explanation: ARR_EXPLANATION, calculation: "$240K × 12 = $2.88M" },
      { id: "market-mint-growth", label: "Revenue Growth", correctTileId: "market-mint-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($240K − $200K) ÷ $200K = 20%" },
    ],
    tilePool: [
      { id: "market-mint-mrr-correct", label: "$240K" },
      { id: "market-mint-mrr-wrong-1", label: "$250K" },
      { id: "market-mint-mrr-wrong-2", label: "$220K" },
      { id: "market-mint-arr-correct", label: "$2.88M" },
      { id: "market-mint-arr-wrong-1", label: "$2.4M" },
      { id: "market-mint-arr-wrong-2", label: "$3M" },
      { id: "market-mint-growth-correct", label: "20%" },
      { id: "market-mint-growth-wrong-1", label: "25%" },
      { id: "market-mint-growth-wrong-2", label: "10%" },
    ],
    verdict: "MRR increased 20%, and expansion revenue alone was twice churned MRR. Growth is being supported by the installed customer base rather than depending entirely on new logos.",
    verdictType: "healthy",
  },
  {
    id: "clinic-grid",
    section: "revenue-growth",
    startupName: "ClinicGrid",
    rawInputs: [
      { label: "Starting MRR", value: "$150K" },
      { label: "New MRR", value: "$12K" },
      { label: "Expansion MRR", value: "$3K" },
      { label: "Churned MRR", value: "$15K" },
    ],
    slots: [
      { id: "clinic-grid-mrr", label: "MRR", correctTileId: "clinic-grid-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$150K + $12K + $3K − $15K = $150K" },
      { id: "clinic-grid-arr", label: "ARR", correctTileId: "clinic-grid-arr-correct", explanation: ARR_EXPLANATION, calculation: "$150K × 12 = $1.8M" },
      { id: "clinic-grid-growth", label: "Revenue Growth", correctTileId: "clinic-grid-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($150K − $150K) ÷ $150K = 0%" },
    ],
    tilePool: [
      { id: "clinic-grid-mrr-correct", label: "$150K" },
      { id: "clinic-grid-mrr-wrong-1", label: "$165K" },
      { id: "clinic-grid-mrr-wrong-2", label: "$147K" },
      { id: "clinic-grid-arr-correct", label: "$1.8M" },
      { id: "clinic-grid-arr-wrong-1", label: "$1.98M" },
      { id: "clinic-grid-arr-wrong-2", label: "$1.5M" },
      { id: "clinic-grid-growth-correct", label: "0%" },
      { id: "clinic-grid-growth-wrong-1", label: "10%" },
      { id: "clinic-grid-growth-wrong-2", label: "2%" },
    ],
    verdict: "New and expansion MRR exactly replaced churn, leaving recurring revenue flat. The company is maintaining scale, but acquisition effort is not producing net growth until retention improves.",
    verdictType: "concerning",
  },
  {
    id: "creator-port",
    section: "revenue-growth",
    startupName: "CreatorPort",
    rawInputs: [
      { label: "Starting MRR", value: "$100K" },
      { label: "New MRR", value: "$8K" },
      { label: "Expansion MRR", value: "$2K" },
      { label: "Churned MRR", value: "$20K" },
    ],
    slots: [
      { id: "creator-port-mrr", label: "MRR", correctTileId: "creator-port-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$100K + $8K + $2K − $20K = $90K" },
      { id: "creator-port-arr", label: "ARR", correctTileId: "creator-port-arr-correct", explanation: ARR_EXPLANATION, calculation: "$90K × 12 = $1.08M" },
      { id: "creator-port-growth", label: "Revenue Growth", correctTileId: "creator-port-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($90K − $100K) ÷ $100K = −10%" },
    ],
    tilePool: [
      { id: "creator-port-mrr-correct", label: "$90K" },
      { id: "creator-port-mrr-wrong-1", label: "$110K" },
      { id: "creator-port-mrr-wrong-2", label: "$88K" },
      { id: "creator-port-arr-correct", label: "$1.08M" },
      { id: "creator-port-arr-wrong-1", label: "$1.2M" },
      { id: "creator-port-arr-wrong-2", label: "$900K" },
      { id: "creator-port-growth-correct", label: "−10%" },
      { id: "creator-port-growth-wrong-1", label: "10%" },
      { id: "creator-port-growth-wrong-2", label: "−20%" },
    ],
    verdict: "Recurring revenue contracted 10% because churn was twice the combined new and expansion MRR. Adding customers cannot stabilize the business while revenue leaves this quickly.",
    verdictType: "unsustainable",
  },
  {
    id: "fleet-base",
    section: "revenue-growth",
    startupName: "FleetBase",
    rawInputs: [
      { label: "Starting MRR", value: "$250K" },
      { label: "New MRR", value: "$20K" },
      { label: "Expansion MRR", value: "$5K" },
      { label: "Churned MRR", value: "$50K" },
    ],
    slots: [
      { id: "fleet-base-mrr", label: "MRR", correctTileId: "fleet-base-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$250K + $20K + $5K − $50K = $225K" },
      { id: "fleet-base-arr", label: "ARR", correctTileId: "fleet-base-arr-correct", explanation: ARR_EXPLANATION, calculation: "$225K × 12 = $2.7M" },
      { id: "fleet-base-growth", label: "Revenue Growth", correctTileId: "fleet-base-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($225K − $250K) ÷ $250K = −10%" },
    ],
    tilePool: [
      { id: "fleet-base-mrr-correct", label: "$225K" },
      { id: "fleet-base-mrr-wrong-1", label: "$275K" },
      { id: "fleet-base-mrr-wrong-2", label: "$220K" },
      { id: "fleet-base-arr-correct", label: "$2.7M" },
      { id: "fleet-base-arr-wrong-1", label: "$3M" },
      { id: "fleet-base-arr-wrong-2", label: "$2.25M" },
      { id: "fleet-base-growth-correct", label: "−10%" },
      { id: "fleet-base-growth-wrong-1", label: "10%" },
      { id: "fleet-base-growth-wrong-2", label: "−20%" },
    ],
    verdict: "MRR declined 10%, with churn removing twice as much revenue as new sales and expansion added. The current recurring base is shrinking despite continued acquisition activity.",
    verdictType: "unsustainable",
  },
  {
    id: "learn-loop",
    section: "revenue-growth",
    startupName: "LearnLoop",
    rawInputs: [
      { label: "Starting MRR", value: "$60K" },
      { label: "New MRR", value: "$4K" },
      { label: "Expansion MRR", value: "$1K" },
      { label: "Churned MRR", value: "$11K" },
    ],
    slots: [
      { id: "learn-loop-mrr", label: "MRR", correctTileId: "learn-loop-mrr-correct", explanation: MRR_EXPLANATION, calculation: "$60K + $4K + $1K − $11K = $54K" },
      { id: "learn-loop-arr", label: "ARR", correctTileId: "learn-loop-arr-correct", explanation: ARR_EXPLANATION, calculation: "$54K × 12 = $648K" },
      { id: "learn-loop-growth", label: "Revenue Growth", correctTileId: "learn-loop-growth-correct", explanation: GROWTH_EXPLANATION, calculation: "($54K − $60K) ÷ $60K = −10%" },
    ],
    tilePool: [
      { id: "learn-loop-mrr-correct", label: "$54K" },
      { id: "learn-loop-mrr-wrong-1", label: "$65K" },
      { id: "learn-loop-mrr-wrong-2", label: "$53K" },
      { id: "learn-loop-arr-correct", label: "$648K" },
      { id: "learn-loop-arr-wrong-1", label: "$720K" },
      { id: "learn-loop-arr-wrong-2", label: "$540K" },
      { id: "learn-loop-growth-correct", label: "−10%" },
      { id: "learn-loop-growth-wrong-1", label: "8.3%" },
      { id: "learn-loop-growth-wrong-2", label: "−20%" },
    ],
    verdict: "Recurring revenue fell 10% because churn more than doubled the combined contribution from new and expanding customers. The company needs to repair retention before growth spending can compound.",
    verdictType: "unsustainable",
  },
];
