export interface VcGuideTerm {
  term: string;
  definition: string;
  vcLens: string;
}

export interface VcGuideSection {
  id: string;
  title: string;
  description: string;
  terms: readonly VcGuideTerm[];
}

export interface VcGuideFormula {
  name: string;
  formula: string;
  note: string;
}

export const VC_GUIDE_SECTIONS: readonly VcGuideSection[] = [
  {
    id: "economics",
    title: "Startup economics",
    description: "How one customer and one unit create—or consume—value.",
    terms: [
      {
        term: "Revenue",
        definition: "Money earned from selling the product or service before expenses are deducted.",
        vcLens: "Revenue scale matters less when growth is expensive, fragile, or low margin.",
      },
      {
        term: "COGS",
        definition: "Direct costs required to deliver the product or service, such as hosting, fulfilment, or support tied to usage.",
        vcLens: "COGS determines how much revenue remains available to fund the rest of the company.",
      },
      {
        term: "Gross profit",
        definition: "Revenue remaining after subtracting cost of goods sold.",
        vcLens: "This is the value available before sales, product, administration, and financing costs.",
      },
      {
        term: "Gross margin",
        definition: "Gross profit expressed as a percentage of revenue.",
        vcLens: "Higher margins can support faster reinvestment, but normal levels vary by business model.",
      },
      {
        term: "Contribution margin",
        definition: "Revenue left after the variable costs associated with serving and acquiring an incremental unit.",
        vcLens: "It tests whether growth improves or worsens the economics at the unit level.",
      },
      {
        term: "ARPU / ARPA",
        definition: "Average recurring revenue per user, account, or customer over a stated period.",
        vcLens: "VCs check whether expansion, pricing, or customer mix is lifting this number over time.",
      },
      {
        term: "CAC",
        definition: "Customer acquisition cost: sales and marketing spend required to win a new customer.",
        vcLens: "CAC should be measured by channel and cohort because a blended average can hide weak acquisition.",
      },
      {
        term: "LTV / CLTV",
        definition: "Estimated value generated by a customer over the full relationship with the company.",
        vcLens: "LTV is assumption-sensitive; retention, margin, cohort age, and expansion all affect its reliability.",
      },
      {
        term: "LTV:CAC ratio",
        definition: "Customer lifetime value compared with the cost required to acquire that customer.",
        vcLens: "It tests whether acquisition creates enough value, but a single benchmark never fits every model.",
      },
      {
        term: "CAC payback",
        definition: "Time required for customer gross profit to recover the original acquisition cost.",
        vcLens: "Shorter payback returns cash sooner and can make growth easier to finance.",
      },
      {
        term: "ACV",
        definition: "Annual contract value: the recurring value of a customer contract normalised to one year.",
        vcLens: "Comparing ACV with CAC and sales-cycle length helps reveal go-to-market efficiency.",
      },
      {
        term: "Unit economics",
        definition: "Revenue, cost, and profit behaviour measured for one customer, order, location, or other core unit.",
        vcLens: "Strong totals can hide a model where every new unit loses money.",
      },
    ],
  },
  {
    id: "growth-retention",
    title: "Growth & retention",
    description: "Whether revenue is recurring, durable, and improving by cohort.",
    terms: [
      {
        term: "MRR",
        definition: "Monthly recurring revenue expected from active subscriptions, excluding one-off revenue.",
        vcLens: "MRR makes recurring growth and changes in the installed customer base easier to compare.",
      },
      {
        term: "ARR",
        definition: "Annual recurring revenue: recurring revenue expressed on a one-year run-rate basis.",
        vcLens: "VCs separate recurring ARR from services and other non-recurring revenue.",
      },
      {
        term: "Revenue growth",
        definition: "Percentage change in revenue between two comparable periods.",
        vcLens: "The quality, durability, and cost of growth matter alongside the headline percentage.",
      },
      {
        term: "Logo churn",
        definition: "Percentage of customers that leave during a period, regardless of customer size.",
        vcLens: "It reveals customer loss that revenue-weighted measures can conceal.",
      },
      {
        term: "Revenue churn",
        definition: "Recurring revenue lost through cancellations and downgrades during a period.",
        vcLens: "Losing a few large customers can make revenue churn much worse than logo churn.",
      },
      {
        term: "GRR",
        definition: "Gross revenue retention: recurring revenue retained before counting upgrades or expansion.",
        vcLens: "GRR isolates how well the existing revenue base is protected.",
      },
      {
        term: "NRR",
        definition: "Net revenue retention: retained recurring revenue after churn, downgrades, and customer expansion.",
        vcLens: "NRR above 100% means the existing customer base grew even before adding new customers.",
      },
      {
        term: "Expansion revenue",
        definition: "Additional revenue from existing customers through upgrades, added seats, or increased usage.",
        vcLens: "Expansion can improve retention economics and reduce dependence on new-logo acquisition.",
      },
      {
        term: "Cohort",
        definition: "A group of customers joined by a shared start period, channel, product, or characteristic.",
        vcLens: "Cohorts show whether newer customers retain and monetise as well as earlier ones.",
      },
      {
        term: "Customer concentration",
        definition: "Share of revenue controlled by a small number of customers.",
        vcLens: "High concentration creates renewal, bargaining, and forecasting risk.",
      },
    ],
  },
  {
    id: "cash-efficiency",
    title: "Cash & efficiency",
    description: "How long the company can operate and what growth costs in cash.",
    terms: [
      {
        term: "Gross burn",
        definition: "Total cash operating expenses during a period, commonly measured monthly.",
        vcLens: "It shows the company's absolute spending level before cash receipts are considered.",
      },
      {
        term: "Net burn",
        definition: "Net decrease in cash during a period after operating cash inflows are included.",
        vcLens: "Net burn connects operating performance directly to financing needs.",
      },
      {
        term: "Runway",
        definition: "Estimated time before available cash is exhausted at the current net burn rate.",
        vcLens: "Short runway weakens negotiating leverage and limits time to reach the next milestone.",
      },
      {
        term: "Burn multiple",
        definition: "Net cash burned compared with net new recurring revenue created over the same period.",
        vcLens: "It asks how many dollars of cash were consumed to add one dollar of recurring revenue.",
      },
      {
        term: "Cash flow",
        definition: "Movement of cash into and out of the company during a period.",
        vcLens: "Accounting revenue does not guarantee the company has enough cash to operate.",
      },
      {
        term: "Break-even",
        definition: "Point at which revenue or gross profit covers the relevant cost base.",
        vcLens: "VCs clarify whether a founder means contribution, operating, EBITDA, or cash break-even.",
      },
      {
        term: "Rule of 40",
        definition: "A contextual software-company heuristic combining growth rate with a profitability or cash-flow margin.",
        vcLens: "It frames the growth-versus-profitability trade-off; it is not a universal early-stage pass mark.",
      },
    ],
  },
  {
    id: "market-deal",
    title: "Market & deal lens",
    description: "The language behind market size, defensibility, and ownership.",
    terms: [
      {
        term: "TAM",
        definition: "Total addressable market: the broad revenue opportunity if the product captured the entire relevant market.",
        vcLens: "A credible TAM starts with realistic customers, pricing, and market boundaries—not a huge global category.",
      },
      {
        term: "SAM",
        definition: "Serviceable available market: the portion of TAM the current product and business model can serve.",
        vcLens: "SAM narrows the opportunity to reachable customer types, regions, and use cases.",
      },
      {
        term: "SOM",
        definition: "Serviceable obtainable market: the share a company can plausibly win in a defined time horizon.",
        vcLens: "SOM should connect market ambition with distribution capacity and competition.",
      },
      {
        term: "Traction",
        definition: "Evidence that customers use, pay for, return to, or recommend the product.",
        vcLens: "The strongest traction is repeatable and improves across cohorts, not a single impressive logo.",
      },
      {
        term: "Product-market fit",
        definition: "Evidence that a defined market strongly values the product and demand is becoming repeatable.",
        vcLens: "Retention and organic pull usually provide stronger evidence than launch attention alone.",
      },
      {
        term: "Moat",
        definition: "A durable advantage that makes the company harder to copy, replace, or compete away.",
        vcLens: "Possible sources include network effects, proprietary data, switching costs, brand, or structural cost advantage.",
      },
      {
        term: "Scalability",
        definition: "Ability to grow output or revenue without costs and complexity rising at the same rate.",
        vcLens: "VC returns generally require a model that can become much larger without breaking operationally.",
      },
      {
        term: "Pre-money valuation",
        definition: "Agreed company value immediately before a new financing is added.",
        vcLens: "It determines the ownership price paid by new investors alongside deal terms.",
      },
      {
        term: "Post-money valuation",
        definition: "Company value immediately after including the new financing.",
        vcLens: "Post-money value helps translate an investment amount into ownership percentage.",
      },
      {
        term: "Investor ownership",
        definition: "Percentage of the company held by an investor after a financing closes.",
        vcLens: "Ownership percentage matters alongside board rights, liquidation preferences, and other deal terms.",
      },
      {
        term: "Founder ownership after financing",
        definition: "The founder's remaining percentage after new shares or equivalents dilute existing holders.",
        vcLens: "A smaller percentage can still become more valuable, but ownership and control are not the same thing.",
      },
      {
        term: "Dilution",
        definition: "Reduction in an existing holder's ownership percentage when new shares or equivalents are issued.",
        vcLens: "Ownership can shrink across rounds even while the value of the remaining stake rises.",
      },
      {
        term: "Cap table",
        definition: "Record of company ownership across founders, employees, and investors.",
        vcLens: "VCs inspect option pools, prior rights, concentration, and whether incentives remain aligned.",
      },
    ],
  },
];

export const VC_GUIDE_FORMULAS: readonly VcGuideFormula[] = [
  {
    name: "Gross profit",
    formula: "Revenue − COGS",
    note: "Use costs directly required to deliver the product or service.",
  },
  {
    name: "Gross margin",
    formula: "(Revenue − COGS) ÷ Revenue",
    note: "Express the result as a percentage.",
  },
  {
    name: "Simple subscription LTV",
    formula: "(Monthly ARPU × Gross Margin) ÷ Monthly Churn",
    note: "A simplified steady-state model; real analyses may use cohort cash flows and expansion.",
  },
  {
    name: "LTV:CAC",
    formula: "LTV ÷ CAC",
    note: "Compare like-for-like customer segments and acquisition cohorts.",
  },
  {
    name: "CAC payback",
    formula: "CAC ÷ Monthly Gross Profit per Customer",
    note: "The Build the Pitch scenarios use ARPU × gross margin for monthly gross profit.",
  },
  {
    name: "Current MRR",
    formula: "Starting MRR + New MRR + Expansion MRR − Churned MRR",
    note: "Use recurring subscription revenue only and keep every movement in the same month.",
  },
  {
    name: "ARR run rate",
    formula: "Current MRR × 12",
    note: "A simple annualized run rate for monthly recurring revenue, not recognized annual revenue.",
  },
  {
    name: "Revenue growth",
    formula: "((Current Revenue − Prior Revenue) ÷ Prior Revenue) × 100",
    note: "Compare equivalent periods and state whether the measure is monthly, quarterly, or annual.",
  },
  {
    name: "Net burn",
    formula: "Cash Outflows − Cash Inflows",
    note: "Use cash movements from the same period; accounting expenses and revenue may differ from cash flow.",
  },
  {
    name: "Runway",
    formula: "Cash Balance ÷ Monthly Net Burn",
    note: "A planning estimate that changes as revenue and spending change.",
  },
  {
    name: "Burn multiple",
    formula: "Net Burn ÷ Net New ARR",
    note: "Use the same time period for both values.",
  },
  {
    name: "Post-money valuation",
    formula: "Pre-money Valuation + New Investment",
    note: "This simple primary-round model may need adjustment for SAFEs, notes, option-pool changes, or secondary sales.",
  },
  {
    name: "Investor ownership",
    formula: "New Investment ÷ Post-money Valuation",
    note: "A simplified primary-equity calculation; ownership can change with other securities and deal terms.",
  },
  {
    name: "Founder ownership after a simple round",
    formula: "Pre-round Founder Ownership × (1 − New Investor Ownership)",
    note: "Assumes proportional dilution in a simple round; option pools, convertibles, and secondary transactions can change the result.",
  },
  {
    name: "Net revenue retention",
    formula: "(Starting Revenue − Churn − Contraction + Expansion) ÷ Starting Revenue",
    note: "Measure only the starting customer base; exclude revenue from new customers.",
  },
];
