export type PitchSignalType = "green" | "red" | "neutral";
export type PitchJudgment = "green" | "red";

export interface FounderPitchLine {
  id: string;
  speaker: string;
  text: string;
  signalType: PitchSignalType;
  whyItMatters?: string;
}

export interface FounderPitchTranscript {
  id: string;
  founderName: string;
  startupContext: string;
  diligenceFocus: string;
  lines: FounderPitchLine[];
}

export const FOUNDER_PITCH_TRANSCRIPTS: readonly FounderPitchTranscript[] = [
  {
    id: "pitch-1",
    founderName: "Mira, founder of LedgerLeaf",
    startupContext: "LedgerLeaf automates cash reconciliation for multi-location hospitality groups and is raising a seed round after a year of paid pilots.",
    diligenceFocus: "Assess customer quality, retention, sales efficiency, and whether the team is responding honestly to early churn.",
    lines: [
      { id: "p1-l1", speaker: "You (VC)", text: "Give me the shortest version of what LedgerLeaf does.", signalType: "neutral" },
      { id: "p1-l2", speaker: "Founder", text: "We reconcile card, delivery-app, and bank payouts for restaurant groups, then flag the mismatches their finance teams currently hunt down by hand.", signalType: "neutral" },
      { id: "p1-l3", speaker: "You (VC)", text: "What traction do you have beyond pilots?", signalType: "neutral" },
      { id: "p1-l4", speaker: "Founder", text: "Eighteen groups pay us today, covering 640 locations. Four more are still unpaid pilots, and I keep those out of recurring revenue.", signalType: "green", whyItMatters: "Separating paying customers from pilots makes the traction claim easier to trust and verify." },
      { id: "p1-l5", speaker: "You (VC)", text: "How has retention looked?", signalType: "neutral" },
      { id: "p1-l6", speaker: "Founder", text: "We lost three early customers. Two never connected all their bank accounts, so we rebuilt onboarding; the third closed half its locations and cut every software bill.", signalType: "green", whyItMatters: "She discloses churn directly, distinguishes its causes, and explains the operational response." },
      { id: "p1-l7", speaker: "You (VC)", text: "What does acquisition cost you?", signalType: "neutral" },
      { id: "p1-l8", speaker: "Founder", text: "About $4,200 per signed group if I include my own sales time at market salary. Without that allocation it looks much prettier, but it isn't honest.", signalType: "green", whyItMatters: "Including founder labor avoids presenting artificially flattering acquisition economics." },
      { id: "p1-l9", speaker: "You (VC)", text: "Who do you compete with?", signalType: "neutral" },
      { id: "p1-l10", speaker: "Founder", text: "Mostly spreadsheets and outsourced bookkeeping. Two funded startups sell adjacent tools; they could move into reconciliation faster than I'd like.", signalType: "green", whyItMatters: "She recognizes both status-quo and emerging competitors rather than claiming an empty market." },
      { id: "p1-l11", speaker: "You (VC)", text: "Why raise now?", signalType: "neutral" },
      { id: "p1-l12", speaker: "Founder", text: "We have fourteen months of runway. The round lets us hire two implementation leads, but if it takes longer, we can pause hiring rather than force bad terms.", signalType: "green", whyItMatters: "The founder knows runway, ties capital to a concrete bottleneck, and retains a credible fallback plan." },
      { id: "p1-l13", speaker: "You (VC)", text: "What would make this round fail?", signalType: "neutral" },
      { id: "p1-l14", speaker: "Founder", text: "If onboarding still needs as much hand-holding after those hires, we may have a services business wearing a software margin. That's the risk I want the next six months to resolve.", signalType: "green", whyItMatters: "Naming the central risk and a timeframe for testing it shows disciplined uncertainty rather than unsupported confidence." },
    ],
  },
  {
    id: "pitch-2",
    founderName: "Dev, founder of FarmRoute",
    startupContext: "FarmRoute connects independent farms with urban restaurants and coordinates next-day produce delivery through regional hubs.",
    diligenceFocus: "Evaluate marketplace liquidity, margin quality, repeat demand, and whether headline growth reflects durable economics.",
    lines: [
      { id: "p2-l1", speaker: "You (VC)", text: "What changed enough in this market for FarmRoute to work now?", signalType: "neutral" },
      { id: "p2-l2", speaker: "Founder", text: "Restaurants want fresher supply, farms want better pricing, and nobody has really connected the two at scale. We're creating the category.", signalType: "red", whyItMatters: "The answer relies on broad assertions and category language without identifying a concrete market change or existing alternatives." },
      { id: "p2-l3", speaker: "You (VC)", text: "How much volume moved through the platform last month?", signalType: "neutral" },
      { id: "p2-l4", speaker: "Founder", text: "Gross merchandise value was $1.2 million, up 240% from the same month last year.", signalType: "neutral" },
      { id: "p2-l5", speaker: "You (VC)", text: "And what did FarmRoute keep from that?", signalType: "neutral" },
      { id: "p2-l6", speaker: "Founder", text: "Our stated take rate is twelve percent. After credits, spoilage, and the delivery subsidies we're using to open cities, realized net revenue is closer to five percent.", signalType: "green", whyItMatters: "The founder distinguishes the headline take rate from what the company actually retains after costly operating adjustments." },
      { id: "p2-l7", speaker: "You (VC)", text: "Are the new cities improving?", signalType: "neutral" },
      { id: "p2-l8", speaker: "Founder", text: "They will. Once density arrives, the economics naturally work — every marketplace follows that curve.", signalType: "red", whyItMatters: "Assuming density will fix economics without evidence from cohorts or mature markets turns a hypothesis into certainty." },
      { id: "p2-l9", speaker: "You (VC)", text: "What does restaurant retention look like?", signalType: "neutral" },
      { id: "p2-l10", speaker: "Founder", text: "Restaurants order when they need us, so monthly churn isn't really the right way to think about the business.", signalType: "red", whyItMatters: "Rejecting the retention question without offering a more appropriate repeat-use metric leaves demand durability unclear." },
      { id: "p2-l11", speaker: "You (VC)", text: "How much runway is left?", signalType: "neutral" },
      { id: "p2-l12", speaker: "Founder", text: "Nine or ten months, depending on expansion. But once investors understand the growth rate, I don't expect financing to be a constraint.", signalType: "red", whyItMatters: "The founder is relying on future fundraising as a certainty despite short runway and unproven city economics." },
      { id: "p2-l13", speaker: "You (VC)", text: "What would you stop doing if this round were smaller?", signalType: "neutral" },
      { id: "p2-l14", speaker: "Founder", text: "Honestly, slowing down would hand the market to someone else. The plan only works if we fund all six launches.", signalType: "red", whyItMatters: "An all-or-nothing expansion plan offers little resilience if capital, demand, or operating assumptions change." },
    ],
  },
  {
    id: "pitch-3",
    founderName: "Elena, founder of ClinicFlow",
    startupContext: "ClinicFlow helps specialist practices reduce appointment no-shows using scheduling automation and patient follow-up workflows.",
    diligenceFocus: "Assess evidence of product impact, healthcare sales maturity, data responsibility, and the credibility of expansion plans.",
    lines: [
      { id: "p3-l1", speaker: "You (VC)", text: "What result are clinics buying from you?", signalType: "neutral" },
      { id: "p3-l2", speaker: "Founder", text: "Fewer empty appointments. Across the 22 clinics live for at least six months, no-shows fell from 14% to 9% on average.", signalType: "green", whyItMatters: "The claim uses a defined cohort, timeframe, baseline, and outcome instead of a broad promise." },
      { id: "p3-l3", speaker: "You (VC)", text: "How do you know your product caused that change?", signalType: "neutral" },
      { id: "p3-l4", speaker: "Founder", text: "We don't fully. There isn't a randomized control, and some clinics also changed reminder policies. We can show correlation and workflow adoption, not clean causation yet.", signalType: "green", whyItMatters: "The founder states the evidence boundary clearly rather than overstating what the data proves." },
      { id: "p3-l5", speaker: "You (VC)", text: "What does the sales process look like?", signalType: "neutral" },
      { id: "p3-l6", speaker: "Founder", text: "Independent practices close in about six weeks. Hospital groups can take nine months, so our forecast keeps them out until procurement is complete.", signalType: "neutral" },
      { id: "p3-l7", speaker: "You (VC)", text: "Any security incidents so far?", signalType: "neutral" },
      { id: "p3-l8", speaker: "Founder", text: "No reportable breach. We did expose appointment metadata in an internal test environment for several hours; we notified the affected clinic and changed access controls.", signalType: "green", whyItMatters: "Volunteering a contained incident and the remediation demonstrates transparency around a sensitive operational risk." },
      { id: "p3-l9", speaker: "You (VC)", text: "How large can this become?", signalType: "neutral" },
      { id: "p3-l10", speaker: "Founder", text: "Every patient interaction is eventually ours — scheduling, intake, billing, maybe clinical decisions. There isn't a meaningful ceiling.", signalType: "red", whyItMatters: "The answer leaps far beyond the proven product and uses an effectively unlimited market claim without a grounded expansion path." },
      { id: "p3-l11", speaker: "You (VC)", text: "Which expansion is actually next?", signalType: "neutral" },
      { id: "p3-l12", speaker: "Founder", text: "Intake forms, because twelve current customers asked for them and six agreed to test a paid add-on.", signalType: "green", whyItMatters: "The near-term roadmap is tied to specific existing-customer demand and willingness to pay." },
      { id: "p3-l13", speaker: "You (VC)", text: "What would you watch most closely after investing?", signalType: "neutral" },
      { id: "p3-l14", speaker: "Founder", text: "Whether support time per clinic falls as we grow. It hasn't yet, and if it stays flat, our margins won't look like software margins.", signalType: "green", whyItMatters: "The founder identifies an unresolved scaling constraint and connects it directly to the business model." },
    ],
  },
  {
    id: "pitch-4",
    founderName: "Jonah, founder of LoopCart",
    startupContext: "LoopCart gives online brands a branded returns portal and routes returned inventory toward resale, refurbishment, or liquidation.",
    diligenceFocus: "Understand the product's differentiation, customer commitment, revenue concentration, and exposure to platform competitors.",
    lines: [
      { id: "p4-l1", speaker: "You (VC)", text: "Why do merchants need another returns tool?", signalType: "neutral" },
      { id: "p4-l2", speaker: "Founder", text: "Most tools stop at printing a label. We decide where an item should go next based on condition, resale value, and warehouse capacity.", signalType: "green", whyItMatters: "The founder identifies a concrete workflow difference rather than describing a generic feature set." },
      { id: "p4-l3", speaker: "You (VC)", text: "How many brands use it?", signalType: "neutral" },
      { id: "p4-l4", speaker: "Founder", text: "Thirty-one are live. Nine are annual contracts, and the rest can leave monthly.", signalType: "green", whyItMatters: "The answer distinguishes total customers from the smaller group with long-term contractual commitment." },
      { id: "p4-l5", speaker: "You (VC)", text: "Is revenue concentrated?", signalType: "neutral" },
      { id: "p4-l6", speaker: "Founder", text: "Our largest brand is 28% of revenue. That's higher than I want, although their renewal is signed for another year.", signalType: "green", whyItMatters: "The founder states a material concentration risk precisely while providing relevant mitigating context." },
      { id: "p4-l7", speaker: "You (VC)", text: "Could the big commerce platforms build this?", signalType: "neutral" },
      { id: "p4-l8", speaker: "Founder", text: "They could build pieces of it. Our defense is the routing data across warehouses and resale channels, but it's early — I wouldn't call it a moat yet.", signalType: "green", whyItMatters: "He acknowledges a credible competitive threat and avoids overstating an emerging data advantage." },
      { id: "p4-l9", speaker: "You (VC)", text: "What happened to margins as volume grew?", signalType: "neutral" },
      { id: "p4-l10", speaker: "Founder", text: "Software gross margin improved; services margin did not. We're separating implementation from subscription pricing next quarter.", signalType: "neutral" },
      { id: "p4-l11", speaker: "You (VC)", text: "What are you raising for?", signalType: "neutral" },
      { id: "p4-l12", speaker: "Founder", text: "Two integrations, one enterprise seller, and enough runway to learn whether larger brands expand after the first warehouse.", signalType: "neutral" },
      { id: "p4-l13", speaker: "You (VC)", text: "Any number in the deck you think needs context?", signalType: "neutral" },
      { id: "p4-l14", speaker: "Founder", text: "The 70% return-to-resale rate comes from our best category, apparel. Across every category it's 46%, and that's the number I'd underwrite.", signalType: "green", whyItMatters: "He corrects a flattering selective metric and points the investor toward the representative company-wide figure." },
    ],
  },
  {
    id: "pitch-5",
    founderName: "Sana, founder of GridNest",
    startupContext: "GridNest forecasts electricity demand for small commercial buildings and recommends when to run flexible equipment to reduce peak charges.",
    diligenceFocus: "Assess technical validation, savings claims, deployment friction, and whether the sales narrative is ahead of the product.",
    lines: [
      { id: "p5-l1", speaker: "You (VC)", text: "What does a customer actually save?", signalType: "neutral" },
      { id: "p5-l2", speaker: "Founder", text: "The median live site saved 8.4% on demand charges over six months. Weather and operating changes also affect that, so we don't claim all of it as causal.", signalType: "green", whyItMatters: "The founder gives a precise cohort result and clearly limits the causal claim." },
      { id: "p5-l3", speaker: "You (VC)", text: "How difficult is installation?", signalType: "neutral" },
      { id: "p5-l4", speaker: "Founder", text: "Our sales deck says one day. In practice the median is three because building data is messy; we're updating the deck this week.", signalType: "green", whyItMatters: "She corrects an outdated favorable claim and provides the real operating figure without being forced." },
      { id: "p5-l5", speaker: "You (VC)", text: "Who validates the recommendations?", signalType: "neutral" },
      { id: "p5-l6", speaker: "Founder", text: "Our model is more accurate than anything utilities use. The engineering team tested it extensively.", signalType: "red", whyItMatters: "A sweeping superiority claim backed only by internal testing lacks the independent or comparative evidence the statement requires." },
      { id: "p5-l7", speaker: "You (VC)", text: "Have customers ever overridden it?", signalType: "neutral" },
      { id: "p5-l8", speaker: "Founder", text: "Frequently in the first month. Facilities managers trust the system after they see it work, so override rates fall from about 40% to 12% by month three.", signalType: "neutral" },
      { id: "p5-l9", speaker: "You (VC)", text: "How are you counting contracted revenue?", signalType: "neutral" },
      { id: "p5-l10", speaker: "Founder", text: "We include three letters of intent in ARR because procurement told us the contracts are essentially administrative now.", signalType: "red", whyItMatters: "Treating non-binding intentions as recurring revenue overstates current commercial traction." },
      { id: "p5-l11", speaker: "You (VC)", text: "What happens if those deals slip?", signalType: "neutral" },
      { id: "p5-l12", speaker: "Founder", text: "We delay the second sales hire and still have eleven months. The product team is funded either way.", signalType: "green", whyItMatters: "The founder has a specific contingency plan that protects core execution if uncertain deals do not close." },
      { id: "p5-l13", speaker: "You (VC)", text: "What are you least certain about?", signalType: "neutral" },
      { id: "p5-l14", speaker: "Founder", text: "Whether small-building savings support our current price without rebates. We have twelve months of renewals to learn that before expanding segments.", signalType: "green", whyItMatters: "She identifies a fundamental pricing risk and explains how current evidence will test it before expansion." },
    ],
  },
  {
    id: "pitch-6",
    founderName: "Theo, founder of CraftCloud",
    startupContext: "CraftCloud helps independent video creators manage sponsorship proposals, contracts, deliverables, and invoicing in one workspace.",
    diligenceFocus: "Evaluate retention, creator willingness to pay, platform dependency, and whether reported growth masks weak engagement.",
    lines: [
      { id: "p6-l1", speaker: "You (VC)", text: "Who is this built for today?", signalType: "neutral" },
      { id: "p6-l2", speaker: "Founder", text: "Creators earning between $50,000 and $500,000 a year from sponsorships. Below that, the workflow usually isn't painful enough yet.", signalType: "green", whyItMatters: "The founder narrows the target customer based on where the problem becomes valuable enough to solve." },
      { id: "p6-l3", speaker: "You (VC)", text: "Your deck says users grew five times. From what base?", signalType: "neutral" },
      { id: "p6-l4", speaker: "Founder", text: "From 400 accounts to just over 2,000. About 620 used the product last month, but sign-ups are the better indicator at this stage.", signalType: "red", whyItMatters: "Preferring cumulative sign-ups over much lower active usage can conceal an engagement or retention problem." },
      { id: "p6-l5", speaker: "You (VC)", text: "How many pay?", signalType: "neutral" },
      { id: "p6-l6", speaker: "Founder", text: "Two hundred and fourteen. Another 170 are on extended creator-partner trials that we expect to convert.", signalType: "neutral" },
      { id: "p6-l7", speaker: "You (VC)", text: "What is monthly churn among paying accounts?", signalType: "neutral" },
      { id: "p6-l8", speaker: "Founder", text: "We haven't settled on a churn definition because creators pause between campaigns. Annual retention will be more meaningful once we have it.", signalType: "red", whyItMatters: "A complicated usage pattern may require a better retention measure, but not tracking any current proxy leaves durability unexamined." },
      { id: "p6-l9", speaker: "You (VC)", text: "How dependent are you on the major video platforms?", signalType: "neutral" },
      { id: "p6-l10", speaker: "Founder", text: "Very. If either platform restricts creator-data access, reporting gets worse. We're building direct brand integrations, but that risk is real today.", signalType: "green", whyItMatters: "The founder acknowledges a material platform dependency and separates the current risk from a future mitigation." },
      { id: "p6-l11", speaker: "You (VC)", text: "What does the round unlock?", signalType: "neutral" },
      { id: "p6-l12", speaker: "Founder", text: "With enough capital we can own the entire creator economy — contracts, payments, banking, even talent management.", signalType: "red", whyItMatters: "The expansion claim is far broader than the product's current adoption and lacks sequencing or evidence." },
      { id: "p6-l13", speaker: "You (VC)", text: "What's the first proof point you'd target?", signalType: "neutral" },
      { id: "p6-l14", speaker: "Founder", text: "Getting paid-account monthly retention above 95%. If we can't do that, adding financial products just hides the core problem.", signalType: "green", whyItMatters: "He defines a measurable near-term test and recognizes that expansion should not distract from weak core retention." },
    ],
  },
  {
    id: "pitch-7",
    founderName: "Priya, founder of Shiftline",
    startupContext: "Shiftline provides scheduling and shift-swap software for regional care-home operators with hourly workforces.",
    diligenceFocus: "Assess buyer urgency, employee adoption, implementation burden, and the founder's discipline around enterprise growth.",
    lines: [
      { id: "p7-l1", speaker: "You (VC)", text: "Who feels the pain strongly enough to buy this?", signalType: "neutral" },
      { id: "p7-l2", speaker: "Founder", text: "Operations directors buy it, but schedulers feel the pain. We lost our first two sales because we sold executives without involving the people building the rota.", signalType: "green", whyItMatters: "The founder distinguishes buyer from user and shows that failed sales changed the go-to-market process." },
      { id: "p7-l3", speaker: "You (VC)", text: "Does staff actually use the swap feature?", signalType: "neutral" },
      { id: "p7-l4", speaker: "Founder", text: "Seventy-two percent of eligible workers used it last quarter. Adoption is 40% at our newest customer, so onboarding quality still matters a lot.", signalType: "green", whyItMatters: "She provides both the portfolio metric and a weaker current cohort instead of presenting only the best result." },
      { id: "p7-l5", speaker: "You (VC)", text: "How long does implementation take?", signalType: "neutral" },
      { id: "p7-l6", speaker: "Founder", text: "Four weeks on average. We tried promising two and created a mess, so now the contract and sales process both say four.", signalType: "green", whyItMatters: "The founder describes a mistake, its consequence, and a concrete correction to avoid repeating it." },
      { id: "p7-l7", speaker: "You (VC)", text: "Your pipeline looks large. How much is qualified?", signalType: "neutral" },
      { id: "p7-l8", speaker: "Founder", text: "$3.8 million is in the CRM, but only $900,000 has a confirmed budget owner and timeline. That's what we plan against.", signalType: "green", whyItMatters: "She separates broad pipeline from genuinely qualified opportunities and forecasts from the more defensible number." },
      { id: "p7-l9", speaker: "You (VC)", text: "What competitor worries you?", signalType: "neutral" },
      { id: "p7-l10", speaker: "Founder", text: "The payroll vendors. Their scheduling is worse, but they already have the contract and distribution. We have to be meaningfully better, not merely nicer.", signalType: "neutral" },
      { id: "p7-l11", speaker: "You (VC)", text: "Where could the business break?", signalType: "neutral" },
      { id: "p7-l12", speaker: "Founder", text: "Implementation could remain people-heavy. Today every new operator needs about thirty hours from us; the round funds tooling to halve that before we add sales capacity.", signalType: "green", whyItMatters: "She quantifies the scaling constraint and sequences operational improvement ahead of accelerating sales." },
      { id: "p7-l13", speaker: "You (VC)", text: "How much runway do you have without this round?", signalType: "neutral" },
      { id: "p7-l14", speaker: "Founder", text: "Sixteen months at current burn, twelve if we make the planned hires. We won't make them until the money is closed.", signalType: "green", whyItMatters: "The founder understands both runway cases and does not spend against financing before it is secured." },
    ],
  },
  {
    id: "pitch-8",
    founderName: "Marco, founder of FreightFox",
    startupContext: "FreightFox matches small manufacturers with unused capacity at regional trucking fleets and manages shipment tracking.",
    diligenceFocus: "Evaluate marketplace defensibility, true margin, customer concentration, and the operational risks behind rapid shipment growth.",
    lines: [
      { id: "p8-l1", speaker: "You (VC)", text: "Why won't brokers copy what you're doing?", signalType: "neutral" },
      { id: "p8-l2", speaker: "Founder", text: "They can't. Our matching engine is proprietary and years ahead of anything else in freight.", signalType: "red", whyItMatters: "A categorical claim of technical invulnerability without evidence overlooks well-funded incumbents and a copyable workflow." },
      { id: "p8-l3", speaker: "You (VC)", text: "How much volume did you handle last quarter?", signalType: "neutral" },
      { id: "p8-l4", speaker: "Founder", text: "Just over 18,000 shipments, nearly triple last year. One manufacturer represented about a third of them.", signalType: "green", whyItMatters: "The founder volunteers a material concentration detail alongside the strong growth figure." },
      { id: "p8-l5", speaker: "You (VC)", text: "What is your gross margin?", signalType: "neutral" },
      { id: "p8-l6", speaker: "Founder", text: "Twenty-two percent before claims and service credits. After those, last quarter was fifteen percent.", signalType: "green", whyItMatters: "He distinguishes a flattering pre-adjustment margin from what the business retained after real operating costs." },
      { id: "p8-l7", speaker: "You (VC)", text: "Have claims changed as volume increased?", signalType: "neutral" },
      { id: "p8-l8", speaker: "Founder", text: "A little, but that's noise. At scale the percentages always normalize.", signalType: "red", whyItMatters: "Dismissing a worsening operational metric as inevitable normalization avoids quantifying a risk that directly affects margin." },
      { id: "p8-l9", speaker: "You (VC)", text: "How do fleets behave when spot prices rise?", signalType: "neutral" },
      { id: "p8-l10", speaker: "Founder", text: "Some leave for higher-priced loads. We haven't seen a full peak market yet, so I can't claim our supply is durable through one.", signalType: "green", whyItMatters: "The founder acknowledges that current supply retention has not been tested under the market condition most likely to weaken it." },
      { id: "p8-l11", speaker: "You (VC)", text: "What does the new capital fund?", signalType: "neutral" },
      { id: "p8-l12", speaker: "Founder", text: "Three more regions and a national sales team. If we're first everywhere, the network effects should lock the market up.", signalType: "red", whyItMatters: "The expansion plan assumes network effects and market lock-in before current regional durability is established." },
      { id: "p8-l13", speaker: "You (VC)", text: "Could you grow more slowly?", signalType: "neutral" },
      { id: "p8-l14", speaker: "Founder", text: "We could open one region at a time and stay near break-even, but I'd rather use the window while competitors are distracted.", signalType: "neutral" },
    ],
  },
  {
    id: "pitch-9",
    founderName: "Aisha, founder of Learnloom",
    startupContext: "Learnloom sells collaborative science-lab simulations to secondary schools that cannot offer every physical experiment.",
    diligenceFocus: "Assess learning evidence, school-budget realities, renewal quality, and whether product enthusiasm translates into a scalable business.",
    lines: [
      { id: "p9-l1", speaker: "You (VC)", text: "What problem are schools hiring you to solve?", signalType: "neutral" },
      { id: "p9-l2", speaker: "Founder", text: "Access. A student can run a genetics experiment their school couldn't safely or affordably run in a physical lab.", signalType: "neutral" },
      { id: "p9-l3", speaker: "You (VC)", text: "Do simulations improve learning outcomes?", signalType: "neutral" },
      { id: "p9-l4", speaker: "Founder", text: "Students using Learnloom improved quiz scores by 18%. It was a teacher-led study in six schools, not an independent trial, so we're funding a larger evaluation now.", signalType: "green", whyItMatters: "The founder shares the positive result while making the study's limited design and sample explicit." },
      { id: "p9-l5", speaker: "You (VC)", text: "Who buys and when?", signalType: "neutral" },
      { id: "p9-l6", speaker: "Founder", text: "Department heads champion us; districts sign. Most decisions happen in a four-month budget window, which makes our revenue seasonal.", signalType: "green", whyItMatters: "She identifies the champion, economic buyer, and timing constraint that shape the real sales process." },
      { id: "p9-l7", speaker: "You (VC)", text: "Your renewal rate is 92%. Any caveat?", signalType: "neutral" },
      { id: "p9-l8", speaker: "Founder", text: "It excludes twelve schools whose grants ended because we classify those as program completions, not churn.", signalType: "red", whyItMatters: "Excluding customers who stopped paying because funding ended can make retention appear stronger than the economic reality." },
      { id: "p9-l9", speaker: "You (VC)", text: "What is renewal if those schools are included?", signalType: "neutral" },
      { id: "p9-l10", speaker: "Founder", text: "Seventy-eight percent. That's the number we use for cash planning, even though the product team tracks the narrower cohort too.", signalType: "green", whyItMatters: "She supplies the economically relevant retention figure and confirms it drives planning despite the deck's favorable presentation." },
      { id: "p9-l11", speaker: "You (VC)", text: "How do you expand within a district?", signalType: "neutral" },
      { id: "p9-l12", speaker: "Founder", text: "We start with biology, then add chemistry and physics after teachers request them. Eight of our last eleven renewals expanded subjects.", signalType: "green", whyItMatters: "Expansion follows observed customer demand and is supported by a specific recent cohort." },
      { id: "p9-l13", speaker: "You (VC)", text: "What would make you slow hiring?", signalType: "neutral" },
      { id: "p9-l14", speaker: "Founder", text: "If this budget cycle produces fewer than twenty district renewals, we pause content hiring and protect eighteen months of runway.", signalType: "green", whyItMatters: "The founder sets a concrete operating trigger and links it to a runway-preserving action." },
    ],
  },
  {
    id: "pitch-10",
    founderName: "Owen, founder of SignalDesk",
    startupContext: "SignalDesk helps mid-sized companies investigate security alerts by connecting evidence from identity, endpoint, and cloud tools.",
    diligenceFocus: "Assess security-product credibility, deployment value, revenue reporting, customer concentration, and burn discipline.",
    lines: [
      { id: "p10-l1", speaker: "You (VC)", text: "What makes SignalDesk different from a security dashboard?", signalType: "neutral" },
      { id: "p10-l2", speaker: "Founder", text: "We don't just aggregate alerts. We build an evidence trail and suggest the next investigation step, so a small team can handle incidents without another analyst.", signalType: "neutral" },
      { id: "p10-l3", speaker: "You (VC)", text: "How do you measure that outcome?", signalType: "neutral" },
      { id: "p10-l4", speaker: "Founder", text: "For customers live over ninety days, median investigation time fell from 52 minutes to 19. The customer controls the final response; we don't claim autonomous remediation.", signalType: "green", whyItMatters: "The answer defines the cohort and measured improvement while clearly limiting what the product does." },
      { id: "p10-l5", speaker: "You (VC)", text: "Your slide says $2 million ARR. Is all of that live?", signalType: "neutral" },
      { id: "p10-l6", speaker: "Founder", text: "$1.5 million is live recurring revenue. The other $500,000 is signed but starts next quarter, so technically it is contracted ARR.", signalType: "red", whyItMatters: "Combining future-start contracts with live ARR can obscure current revenue and should be labeled separately." },
      { id: "p10-l7", speaker: "You (VC)", text: "How concentrated is that revenue?", signalType: "neutral" },
      { id: "p10-l8", speaker: "Founder", text: "Our largest customer is 34% of live ARR. They're happy, and security contracts are extremely sticky.", signalType: "red", whyItMatters: "Material concentration remains a risk even when the customer is satisfied; calling contracts inherently sticky substitutes confidence for renewal evidence." },
      { id: "p10-l9", speaker: "You (VC)", text: "Have you had a renewal cycle with them?", signalType: "neutral" },
      { id: "p10-l10", speaker: "Founder", text: "Not yet. Their first renewal is in five months, and losing them would force us to reset the hiring plan.", signalType: "green", whyItMatters: "He corrects the implied certainty and states the operational consequence of the untested renewal." },
      { id: "p10-l11", speaker: "You (VC)", text: "What's your burn today?", signalType: "neutral" },
      { id: "p10-l12", speaker: "Founder", text: "About $310,000 a month net. We cut three planned roles when two deals slipped, which keeps seventeen months of runway.", signalType: "green", whyItMatters: "The founder knows current burn and runway and has already adjusted hiring when sales timing changed." },
      { id: "p10-l13", speaker: "You (VC)", text: "What can't you prove yet?", signalType: "neutral" },
      { id: "p10-l14", speaker: "Founder", text: "Whether a five-person security team gets the same value as our ten-person design partners. This round is for proving that segment, not pretending we already have.", signalType: "green", whyItMatters: "He distinguishes proven design-partner value from the next market hypothesis the capital is intended to test." },
    ],
  },
];
