"use client";
import { useCallback, useEffect, useReducer, useRef, useState } from "react";
import { useEntryEnterShortcut } from "@/app/(app)/mini-games/vc-games/_lib/use-entry-enter-shortcut";
import { MiniGameShell } from "@/components/mini-games/MiniGameShell";
import { useMiniGameResultSync } from "@/components/mini-games/use-mini-game-result-sync";
import { ActiveWorkPanel } from "./_components/ActiveWorkPanel";
import { AllNighterIntro } from "./_components/AllNighterIntro";
import { AllNighterGuide } from "./_components/AllNighterGuide";
import { AllNighterResults } from "./_components/AllNighterResults";
import { TaskQueue } from "./_components/TaskQueue";
import { allNighterScenarios } from "./_data/all-nighter-scenarios";
import { formatRemaining } from "./_lib/all-nighter-engine";
import { readAllNighterGuideSeen, saveAllNighterGuideSeen } from "./_lib/all-nighter-guide-persistence";
import { ALL_NIGHTER_STORAGE_KEY, ALL_NIGHTER_STORAGE_VERSION, allNighterReducer, INITIAL_ALL_NIGHTER_STATE } from "./_lib/all-nighter-state";
import { markAllNighterScenarioSeen, selectAllNighterScenario } from "./_lib/select-all-nighter-scenario";
import { validateAllNighterScenarios } from "./_lib/validate-all-nighter-scenarios";
import styles from "./the-all-nighter.module.css";

export function AllNighter() { const [state, dispatch] = useReducer(allNighterReducer, INITIAL_ALL_NIGHTER_STATE); const [hydrated, setHydrated] = useState(false); const [guide, setGuide] = useState<"automatic"|"manual"|null>(null); const [guideStep,setGuideStep]=useState(0); const [pendingScenario,setPendingScenario]=useState<ReturnType<typeof selectAllNighterScenario>|null>(null); const activeHeadingRef = useRef<HTMLHeadingElement>(null); const queueRef = useRef<HTMLElement>(null); const resultsRef = useRef<HTMLDivElement>(null); const announcementRef = useRef<HTMLParagraphElement>(null);
  useEffect(() => { /* eslint-disable react-hooks/set-state-in-effect -- one-time optional browser-storage hydration */ try { const stored = JSON.parse(window.localStorage.getItem(ALL_NIGHTER_STORAGE_KEY) ?? "null") as { version?: number; seenScenarioIds?: unknown }; if (stored?.version === ALL_NIGHTER_STORAGE_VERSION && Array.isArray(stored.seenScenarioIds) && stored.seenScenarioIds.every((id) => typeof id === "string")) dispatch({ type: "HYDRATE", seenScenarioIds: stored.seenScenarioIds }); } catch {} setHydrated(true); /* eslint-enable react-hooks/set-state-in-effect */ }, []);
  useEffect(() => { if (hydrated) try { window.localStorage.setItem(ALL_NIGHTER_STORAGE_KEY, JSON.stringify({ version: ALL_NIGHTER_STORAGE_VERSION, seenScenarioIds: state.seenScenarioIds })); } catch {} }, [hydrated, state.seenScenarioIds]);
  const seenFor = useCallback(() => state.activeScenario ? markAllNighterScenarioSeen(allNighterScenarios, state.seenScenarioIds, state.activeScenario.id) : state.seenScenarioIds, [state.activeScenario, state.seenScenarioIds]);
  useEffect(() => { if (state.phase !== "active") return; let frame = 0; let timer = 0; const tick = () => { dispatch({ type: "RECONCILE", now: performance.now(), seenScenarioIds: seenFor() }); frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); const reconcileOnVisible = () => { if (!document.hidden) dispatch({ type: "RECONCILE", now: performance.now(), seenScenarioIds: seenFor() }); }; document.addEventListener("visibilitychange", reconcileOnVisible); timer = window.setInterval(reconcileOnVisible, 1000); return () => { cancelAnimationFrame(frame); window.clearInterval(timer); document.removeEventListener("visibilitychange", reconcileOnVisible); }; }, [state.phase, seenFor]);
  useEffect(() => { const event = state.events.at(-1); if (!event || !announcementRef.current || !state.activeScenario) return; const task = event.taskId ? state.activeScenario.taskSchedule.find((item) => item.id === event.taskId) : null; announcementRef.current.textContent = event.type === "arrived" ? `New task arrived: ${task?.description}` : event.type === "missed" ? `Task missed: ${task?.description}` : event.type === "handled" ? `Task handled: ${task?.description}` : event.type === "sessionEnded" ? "Session ended. Results are ready." : `Started task: ${task?.description}`; }, [state.events, state.activeScenario]);
  useEffect(() => { const event = state.events.at(-1); if (event?.type !== "missed" || !queueRef.current) return; window.requestAnimationFrame(() => { const next = queueRef.current?.querySelector<HTMLButtonElement>("button:not(:disabled)"); if (next) next.focus(); else queueRef.current?.querySelector<HTMLElement>("h2")?.focus(); }); }, [state.events]);
  useEffect(() => { if (state.phase === "results") resultsRef.current?.querySelector<HTMLElement>("h1")?.focus(); }, [state.phase]);
  // Report the finished run to /api/mini-games/progress (idempotent per run).
  const syncResult = useMiniGameResultSync();
  useEffect(() => { if (state.phase !== "results" || !state.finalSnapshot) return; const snapshot = state.finalSnapshot; const handled = snapshot.results.filter((item) => item.status === "handled").length; const missed = snapshot.results.filter((item) => item.status === "missed").length; const leftUnhandled = snapshot.results.length - handled - missed; const outcome = handled === snapshot.results.length ? "all-handled" : missed > 0 ? "tasks-missed" : "tasks-left-unhandled"; syncResult({ score: snapshot.results.length > 0 ? Math.round((handled / snapshot.results.length) * 100) : null, outcome, completed: true }); }, [state.phase, state.finalSnapshot, syncResult]);
  const begin = useCallback((scenario: ReturnType<typeof selectAllNighterScenario>) => { dispatch({ type: "START", scenario, now: performance.now() }); setPendingScenario(null); setGuide(null); }, []);
  const start = useCallback(() => { validateAllNighterScenarios(allNighterScenarios); const selected=selectAllNighterScenario(allNighterScenarios,state.seenScenarioIds); if(readAllNighterGuideSeen()) begin(selected); else {setPendingScenario(selected);setGuideStep(0);setGuide("automatic");} }, [state.seenScenarioIds,begin]);
  useEntryEnterShortcut(hydrated && state.phase === "ready", start);
  const handle = useCallback((taskId: string) => { dispatch({ type: "HANDLE", taskId, now: performance.now(), seenScenarioIds: seenFor() }); window.requestAnimationFrame(() => activeHeadingRef.current?.focus()); }, [seenFor]);
  const scenario = state.activeScenario; const sessionRemaining = state.sessionEndAt == null ? 0 : state.sessionEndAt - state.now;
  return <MiniGameShell gameLabel="The All-Nighter" hubHref="/mini-games/investment-banking-games" backLabel="Investment Banking Games" rightContent={state.phase === "active" ? <p className={styles.shellStatus}>Session live</p> : null}><p ref={announcementRef} className={styles.srOnly} aria-live="polite" aria-atomic="true" />{state.phase === "ready" ? <AllNighterIntro ready={hydrated} onStart={start} onGuide={()=>{setGuideStep(0);setGuide("manual");}} /> : null}{scenario && state.phase === "active" ? <div className={styles.desk}><header className={styles.deskHeader}><div><p className={styles.eyebrow}>Live deal queue</p><h1>The All-Nighter</h1><p>{scenario.dealContextNote}</p></div><div className={styles.sessionTimer}><span>Session remaining</span><strong>{formatRemaining(sessionRemaining)}</strong></div></header><div className={styles.grid}><TaskQueue scenario={scenario} tasks={state.tasks} now={state.now} busy={state.activeTaskId != null} onHandle={handle} queueRef={queueRef} /><ActiveWorkPanel scenario={scenario} tasks={state.tasks} activeTaskId={state.activeTaskId} now={state.now} headingRef={activeHeadingRef} /></div></div> : null}{state.phase === "results" && state.finalSnapshot ? <div ref={resultsRef}><AllNighterResults snapshot={state.finalSnapshot} onTryAnother={start} /></div> : null}{guide ? <AllNighterGuide step={guideStep} manual={guide==="manual"} onStep={setGuideStep} onDismiss={()=>{setGuide(null);setPendingScenario(null);}} onSkip={()=>{saveAllNighterGuideSeen();if(guide==="automatic"&&pendingScenario)begin(pendingScenario);else setGuide(null);}} onFinish={()=>{saveAllNighterGuideSeen();if(guide==="automatic"&&pendingScenario)begin(pendingScenario);else setGuide(null);}} /> : null}</MiniGameShell>; }
