import type { FootballFieldScenario } from "../_lib/football-field-types";

export const footballFieldScenarios: FootballFieldScenario[] = [
  { id: "ff-1", targetCompanyName: "TechCore Analytics", dealContextNote: "TechCore is being acquired by a larger enterprise software company looking to add its data analytics platform to an existing product suite.", axisMin: 30, axisMax: 90, axisStep: 1, axisUnit: "$ per share", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "The approved DCF sensitivity cases produce implied values of approximately $55, $61, and $68 per share across the downside, base, and upside assumptions.", referenceLow: 55, referenceHigh: 68, toleranceAmount: 3 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "The selected enterprise-software peer set implies equity values around $50, $56, and $62 per share across the relevant trading-multiple range.", referenceLow: 50, referenceHigh: 62, toleranceAmount: 3 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Recent strategic software acquisitions imply values ranging from roughly $60 per share at the low end to $75 per share at the high end, with several transactions clustering in the upper $60s.", referenceLow: 60, referenceHigh: 75, toleranceAmount: 3 },
  ], actualDealPrice: 66, resultSummary: "In the reference analysis, Precedent Transactions ran meaningfully higher than the other two methods. That is common because past M&A deals often include a control premium that a standalone DCF or public trading comps may not fully reflect. The $66 deal price landed comfortably inside the reference football field, consistent with a strategic buyer paying for full control." },
  { id: "ff-2", targetCompanyName: "Ferrostone Industrial", dealContextNote: "Ferrostone manufactures specialized components using a proprietary manufacturing process. It is being acquired by a competitor seeking to eliminate a key rival and absorb its unique production capacity.", axisMin: 500, axisMax: 1300, axisStep: 10, axisUnit: "$M enterprise value", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "The operating-case sensitivities imply enterprise values of approximately $800M in the downside case, $875M in the base case, and $950M in the upside case.", referenceLow: 800, referenceHigh: 950, toleranceAmount: 25 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "Applying the selected industrial peer multiples produces implied enterprise values of roughly $750M, $815M, and $880M across the observed multiple range.", referenceLow: 750, referenceHigh: 880, toleranceAmount: 25 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Relevant strategic industrial acquisitions imply enterprise values from approximately $900M to $1.10B, with the strongest precedent observations around $1.0B.", referenceLow: 900, referenceHigh: 1100, toleranceAmount: 25 },
  ], actualDealPrice: 1150, resultSummary: "The reference analysis did not capture the $1.15B transaction price even at the top of the Precedent Transactions range. The buyer placed additional value on eliminating a direct competitor and acquiring genuinely differentiated manufacturing capacity. A well-built football field is a strong valuation framework, but strategic value can still push an actual transaction beyond the ranges produced by standard methodologies." },
  { id: "ff-3", targetCompanyName: "Bellwood Consumer Brands", dealContextNote: "Bellwood is a stable, moderately growing consumer packaged-goods company being acquired by a larger portfolio holding company in a straightforward, non-contested sale process.", axisMin: 15, axisMax: 45, axisStep: 1, axisUnit: "$ per share", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "Bellwood's approved cash-flow sensitivities produce implied equity values of approximately $24, $27, and $30 per share.", referenceLow: 24, referenceHigh: 30, toleranceAmount: 2 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "The selected packaged-goods peer set implies approximately $26 per share at the low end, around $30 in the middle of the range, and $33 at the high end.", referenceLow: 26, referenceHigh: 33, toleranceAmount: 2 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Comparable consumer transactions imply approximately $28 to $36 per share, including the control premiums paid in recent acquisitions.", referenceLow: 28, referenceHigh: 36, toleranceAmount: 2 },
  ], actualDealPrice: 29, resultSummary: "This is close to the textbook football-field case. The three reference methodologies form a relatively tight, overlapping valuation band, and the $29 deal price falls comfortably inside it. Stable businesses in non-contested sale processes often produce better agreement between DCF, public comps, and precedent transactions than more unusual or strategically contested assets." },
  { id: "ff-4", targetCompanyName: "Vantage Biotech", dealContextNote: "Vantage is a clinical-stage biotech with a promising but unproven drug pipeline. It is being acquired by a large pharmaceutical company betting on the pipeline's long-term potential.", axisMin: 0, axisMax: 50, axisStep: 1, axisUnit: "$ per share", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "Probability-adjusted pipeline sensitivities produce an unusually wide set of outcomes, ranging from roughly $10 per share in the downside case to approximately $45 per share if the most important clinical assumptions succeed.", referenceLow: 10, referenceHigh: 45, toleranceAmount: 4 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "The limited set of reasonably comparable public biotech companies implies approximately $18 to $25 per share, though the peer set is imperfect because development pipelines differ materially.", referenceLow: 18, referenceHigh: 25, toleranceAmount: 4 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Recent pharmaceutical acquisitions of clinical-stage pipeline companies imply approximately $30 to $42 per share after applying observed transaction multiples and premiums.", referenceLow: 30, referenceHigh: 42, toleranceAmount: 4 },
  ], actualDealPrice: 38, resultSummary: "The reference DCF range is unusually wide because a clinical-stage biotech's value is highly sensitive to whether unproven drugs ultimately succeed. Comparable Companies is much narrower but less informative because truly similar public peers are scarce. Precedent Transactions proved more useful in this case: the $38 acquisition price landed inside that reference range and reflected what pharmaceutical buyers had actually paid for comparable pipeline risk." },
  { id: "ff-5", targetCompanyName: "Palisade Retail Holdings", dealContextNote: "Palisade is a struggling retail chain facing a debt maturity it cannot refinance on its own. It is being acquired by a private equity firm in a rushed, distressed sale process with limited competing interest.", axisMin: 5, axisMax: 30, axisStep: 1, axisUnit: "$ per share", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "The standalone cash-flow cases imply approximately $14 to $19 per share, assuming the company continues operating through the forecast period and executes its restructuring plan.", referenceLow: 14, referenceHigh: 19, toleranceAmount: 2 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "Selected challenged-retail peers imply approximately $12 to $17 per share based on current public-market trading multiples.", referenceLow: 12, referenceHigh: 17, toleranceAmount: 2 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Recent retail acquisitions imply approximately $15 to $20 per share, although most of those sellers had more time and negotiating flexibility than Palisade currently has.", referenceLow: 15, referenceHigh: 20, toleranceAmount: 2 },
  ], actualDealPrice: 10, resultSummary: "The $10 deal price fell below every methodology in the reference football field. Palisade's approaching debt maturity and lack of refinancing alternatives weakened its negotiating position enough to overwhelm the valuation ranges suggested by ordinary fundamentals. Valuation analysis estimates economic value; it cannot guarantee the price a distressed seller will actually have the leverage to achieve." },
  { id: "ff-6", targetCompanyName: "Brightline Cloud Systems", dealContextNote: "Brightline operates in a cloud-infrastructure niche that public markets have recently become very enthusiastic about, pushing valuations across the sector sharply higher. It is being acquired by a strategic buyer deciding how much of that market optimism it is willing to pay for.", axisMin: 20, axisMax: 100, axisStep: 1, axisUnit: "$ per share", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "The company's fundamental cash-flow cases imply approximately $42 to $55 per share across the approved discount-rate and long-term growth sensitivities.", referenceLow: 42, referenceHigh: 55, toleranceAmount: 3 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "Public cloud-infrastructure peers are trading at elevated multiples that imply approximately $68 to $85 per share for Brightline.", referenceLow: 68, referenceHigh: 85, toleranceAmount: 3 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Recent acquisitions in adjacent infrastructure-software categories imply approximately $45 to $58 per share.", referenceLow: 45, referenceHigh: 58, toleranceAmount: 3 },
  ], actualDealPrice: 52, resultSummary: "Comparable Companies is the clear outlier in the reference field, reflecting unusually elevated public-market multiples for the sector. The $52 transaction price landed much closer to DCF and Precedent Transactions, suggesting the acquirer declined to capitalize all of the optimism currently embedded in public comps. Trading comps are useful, but they can become distorted when an entire sector is temporarily priced around unusually aggressive expectations." },
  { id: "ff-7", targetCompanyName: "Corrigan Logistics Group", dealContextNote: "Corrigan is a mid-sized logistics company being acquired roughly two years after a wave of similar logistics transactions closed. Interest rates have risen substantially since those deals, changing what buyers can justify paying today.", axisMin: 200, axisMax: 700, axisStep: 10, axisUnit: "$M enterprise value", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "Using today's higher discount rate, Corrigan's cash-flow sensitivities imply enterprise values of approximately $320M to $380M.", referenceLow: 320, referenceHigh: 380, toleranceAmount: 20 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "Current public logistics-company trading multiples imply approximately $310M to $370M of enterprise value.", referenceLow: 310, referenceHigh: 370, toleranceAmount: 20 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "The most relevant logistics acquisitions from roughly two years ago imply approximately $420M to $500M, but those transactions were completed when financing costs were materially lower.", referenceLow: 420, referenceHigh: 500, toleranceAmount: 20 },
  ], actualDealPrice: 350, resultSummary: "Precedent Transactions sits materially above DCF and Comparable Companies in the reference analysis because those prior deals occurred in a lower-rate environment. The $350 transaction price landed much closer to the two methodologies reflecting today's cost of capital. Precedent transactions are most useful when the market and financing conditions surrounding those deals remain genuinely comparable to the current transaction." },
  { id: "ff-8", targetCompanyName: "Winslow Manufacturing Co.", dealContextNote: "Winslow is a solid, unremarkable industrial manufacturer being acquired by a private equity firm rather than a strategic competitor. There are no major product overlaps or cost synergies to justify a strategic premium; the buyer must earn its return primarily from the company's standalone performance.", axisMin: 20, axisMax: 60, axisStep: 1, axisUnit: "$ per share", methodologies: [
    { id: "dcf", label: "Discounted Cash Flow", analystEvidence: "Winslow's approved standalone operating cases imply approximately $32 to $40 per share across the DCF sensitivity range.", referenceLow: 32, referenceHigh: 40, toleranceAmount: 2 },
    { id: "comps", label: "Comparable Companies", analystEvidence: "Selected public industrial peers imply approximately $30 to $38 per share based on current trading multiples.", referenceLow: 30, referenceHigh: 38, toleranceAmount: 2 },
    { id: "precedentTransactions", label: "Precedent Transactions", analystEvidence: "Recent industrial acquisitions imply approximately $36 to $46 per share, with several strategic transactions incorporating premiums for synergies that a financial sponsor would not receive.", referenceLow: 36, referenceHigh: 46, toleranceAmount: 2 },
  ], actualDealPrice: 34, resultSummary: "The $34 transaction price landed near DCF and Comparable Companies and below much of the Precedent Transactions reference range. That distinction matters because many precedent deals involve strategic acquirers willing to pay for cost savings or product synergies. A private equity sponsor without those benefits must justify its purchase price primarily through the target's standalone cash flows and its required investment return." },
];
